import { expect, test } from "vitest";

import { LANGUAGES, toSentence } from "../app/toSentence";

const cases: Array<[number, string, string]> = [
  [1, "one", "uno"],
  [2, "two", "dos"],
  [3, "three", "tres"],
  [4, "four", "cuatro"],
  [5, "five", "cinco"],
  [6, "six", "seis"],
  [7, "seven", "siete"],
  [8, "eight", "ocho"],
  [9, "nine", "nueve"],
  [10, "ten", "diez"],
  [11, "eleven", "once"],
  [12, "twelve", "doce"],
  [13, "thirteen", "trece"],
  [14, "fourteen", "catorce"],
  [15, "fifteen", "quince"],
  [16, "sixteen", "dieciséis"],
  [17, "seventeen", "diecisiete"],
  [18, "eighteen", "dieciocho"],
  [19, "nineteen", "diecinueve"],
  [20, "twenty", "veinte"],
  [21, "twenty-one", "veintiuno"],
  [22, "twenty-two", "veintidós"],
  [23, "twenty-three", "veintitrés"],
  [24, "twenty-four", "veinticuatro"],
  [25, "twenty-five", "veinticinco"],
  [26, "twenty-six", "veintiséis"],
  [27, "twenty-seven", "veintisiete"],
  [28, "twenty-eight", "veintiocho"],
  [29, "twenty-nine", "veintinueve"],
  [30, "thirty", "treinta"],
  [31, "thirty-one", "treinta y uno"],
  [32, "thirty-two", "treinta y dos"],
  [33, "thirty-three", "treinta y tres"],
  [34, "thirty-four", "treinta y cuatro"],
  [35, "thirty-five", "treinta y cinco"],
  [36, "thirty-six", "treinta y seis"],
  [37, "thirty-seven", "treinta y siete"],
  [38, "thirty-eight", "treinta y ocho"],
  [39, "thirty-nine", "treinta y nueve"],
  [40, "forty", "cuarenta"],
  [41, "forty-one", "cuarenta y uno"],
  [42, "forty-two", "cuarenta y dos"],
  [43, "forty-three", "cuarenta y tres"],
  [44, "forty-four", "cuarenta y cuatro"],
  [45, "forty-five", "cuarenta y cinco"],
  [46, "forty-six", "cuarenta y seis"],
  [47, "forty-seven", "cuarenta y siete"],
  [48, "forty-eight", "cuarenta y ocho"],
  [49, "forty-nine", "cuarenta y nueve"],
  [50, "fifty", "cincuenta"],
  [51, "fifty-one", "cincuenta y uno"],
  [52, "fifty-two", "cincuenta y dos"],
  [53, "fifty-three", "cincuenta y tres"],
  [54, "fifty-four", "cincuenta y cuatro"],
  [55, "fifty-five", "cincuenta y cinco"],
  [56, "fifty-six", "cincuenta y seis"],
  [57, "fifty-seven", "cincuenta y siete"],
  [58, "fifty-eight", "cincuenta y ocho"],
  [59, "fifty-nine", "cincuenta y nueve"],
  [60, "sixty", "sesenta"],
  [61, "sixty-one", "sesenta y uno"],
  [62, "sixty-two", "sesenta y dos"],
  [63, "sixty-three", "sesenta y tres"],
  [64, "sixty-four", "sesenta y cuatro"],
  [65, "sixty-five", "sesenta y cinco"],
  [66, "sixty-six", "sesenta y seis"],
  [67, "sixty-seven", "sesenta y siete"],
  [68, "sixty-eight", "sesenta y ocho"],
  [69, "sixty-nine", "sesenta y nueve"],
  [70, "seventy", "setenta"],
  [71, "seventy-one", "setenta y uno"],
  [72, "seventy-two", "setenta y dos"],
  [73, "seventy-three", "setenta y tres"],
  [74, "seventy-four", "setenta y cuatro"],
  [75, "seventy-five", "setenta y cinco"],
  [76, "seventy-six", "setenta y seis"],
  [77, "seventy-seven", "setenta y siete"],
  [78, "seventy-eight", "setenta y ocho"],
  [79, "seventy-nine", "setenta y nueve"],
  [80, "eighty", "ochenta"],
  [81, "eighty-one", "ochenta y uno"],
  [82, "eighty-two", "ochenta y dos"],
  [83, "eighty-three", "ochenta y tres"],
  [84, "eighty-four", "ochenta y cuatro"],
  [85, "eighty-five", "ochenta y cinco"],
  [86, "eighty-six", "ochenta y seis"],
  [87, "eighty-seven", "ochenta y siete"],
  [88, "eighty-eight", "ochenta y ocho"],
  [89, "eighty-nine", "ochenta y nueve"],
  [90, "ninety", "noventa"],
  [91, "ninety-one", "noventa y uno"],
  [92, "ninety-two", "noventa y dos"],
  [93, "ninety-three", "noventa y tres"],
  [94, "ninety-four", "noventa y cuatro"],
  [95, "ninety-five", "noventa y cinco"],
  [96, "ninety-six", "noventa y seis"],
  [97, "ninety-seven", "noventa y siete"],
  [98, "ninety-eight", "noventa y ocho"],
  [99, "ninety-nine", "noventa y nueve"],
  [100, "one hundred", "cien"],
  [101, "one hundred one", "ciento uno"],
  [102, "one hundred two", "ciento dos"],
  [103, "one hundred three", "ciento tres"],
  [104, "one hundred four", "ciento cuatro"],
  [105, "one hundred five", "ciento cinco"],
  [106, "one hundred six", "ciento seis"],
  [107, "one hundred seven", "ciento siete"],
  [108, "one hundred eight", "ciento ocho"],
  [109, "one hundred nine", "ciento nueve"],
  [110, "one hundred ten", "ciento diez"],
  [111, "one hundred eleven", "ciento once"],
  [112, "one hundred twelve", "ciento doce"],
  [113, "one hundred thirteen", "ciento trece"],
  [114, "one hundred fourteen", "ciento catorce"],
  [115, "one hundred fifteen", "ciento quince"],
  [116, "one hundred sixteen", "ciento dieciséis"],
  [117, "one hundred seventeen", "ciento diecisiete"],
  [118, "one hundred eighteen", "ciento dieciocho"],
  [119, "one hundred nineteen", "ciento diecinueve"],
  [120, "one hundred twenty", "ciento veinte"],
  [121, "one hundred twenty-one", "ciento veintiuno"],
  [122, "one hundred twenty-two", "ciento veintidós"],
  [123, "one hundred twenty-three", "ciento veintitrés"],
  [124, "one hundred twenty-four", "ciento veinticuatro"],
  [125, "one hundred twenty-five", "ciento veinticinco"],
  [126, "one hundred twenty-six", "ciento veintiséis"],
  [127, "one hundred twenty-seven", "ciento veintisiete"],
  [128, "one hundred twenty-eight", "ciento veintiocho"],
  [129, "one hundred twenty-nine", "ciento veintinueve"],
  [130, "one hundred thirty", "ciento treinta"],
  [131, "one hundred thirty-one", "ciento treinta y uno"],
  [132, "one hundred thirty-two", "ciento treinta y dos"],
  [133, "one hundred thirty-three", "ciento treinta y tres"],
  [134, "one hundred thirty-four", "ciento treinta y cuatro"],
  [135, "one hundred thirty-five", "ciento treinta y cinco"],
  [136, "one hundred thirty-six", "ciento treinta y seis"],
  [137, "one hundred thirty-seven", "ciento treinta y siete"],
  [138, "one hundred thirty-eight", "ciento treinta y ocho"],
  [139, "one hundred thirty-nine", "ciento treinta y nueve"],
  [140, "one hundred forty", "ciento cuarenta"],
  [141, "one hundred forty-one", "ciento cuarenta y uno"],
  [142, "one hundred forty-two", "ciento cuarenta y dos"],
  [143, "one hundred forty-three", "ciento cuarenta y tres"],
  [144, "one hundred forty-four", "ciento cuarenta y cuatro"],
  [145, "one hundred forty-five", "ciento cuarenta y cinco"],
  [146, "one hundred forty-six", "ciento cuarenta y seis"],
  [147, "one hundred forty-seven", "ciento cuarenta y siete"],
  [148, "one hundred forty-eight", "ciento cuarenta y ocho"],
  [149, "one hundred forty-nine", "ciento cuarenta y nueve"],
  [150, "one hundred fifty", "ciento cincuenta"],
  [151, "one hundred fifty-one", "ciento cincuenta y uno"],
  [152, "one hundred fifty-two", "ciento cincuenta y dos"],
  [153, "one hundred fifty-three", "ciento cincuenta y tres"],
  [154, "one hundred fifty-four", "ciento cincuenta y cuatro"],
  [155, "one hundred fifty-five", "ciento cincuenta y cinco"],
  [156, "one hundred fifty-six", "ciento cincuenta y seis"],
  [157, "one hundred fifty-seven", "ciento cincuenta y siete"],
  [158, "one hundred fifty-eight", "ciento cincuenta y ocho"],
  [159, "one hundred fifty-nine", "ciento cincuenta y nueve"],
  [160, "one hundred sixty", "ciento sesenta"],
  [161, "one hundred sixty-one", "ciento sesenta y uno"],
  [162, "one hundred sixty-two", "ciento sesenta y dos"],
  [163, "one hundred sixty-three", "ciento sesenta y tres"],
  [164, "one hundred sixty-four", "ciento sesenta y cuatro"],
  [165, "one hundred sixty-five", "ciento sesenta y cinco"],
  [166, "one hundred sixty-six", "ciento sesenta y seis"],
  [167, "one hundred sixty-seven", "ciento sesenta y siete"],
  [168, "one hundred sixty-eight", "ciento sesenta y ocho"],
  [169, "one hundred sixty-nine", "ciento sesenta y nueve"],
  [170, "one hundred seventy", "ciento setenta"],
  [171, "one hundred seventy-one", "ciento setenta y uno"],
  [172, "one hundred seventy-two", "ciento setenta y dos"],
  [173, "one hundred seventy-three", "ciento setenta y tres"],
  [174, "one hundred seventy-four", "ciento setenta y cuatro"],
  [175, "one hundred seventy-five", "ciento setenta y cinco"],
  [176, "one hundred seventy-six", "ciento setenta y seis"],
  [177, "one hundred seventy-seven", "ciento setenta y siete"],
  [178, "one hundred seventy-eight", "ciento setenta y ocho"],
  [179, "one hundred seventy-nine", "ciento setenta y nueve"],
  [180, "one hundred eighty", "ciento ochenta"],
  [181, "one hundred eighty-one", "ciento ochenta y uno"],
  [182, "one hundred eighty-two", "ciento ochenta y dos"],
  [183, "one hundred eighty-three", "ciento ochenta y tres"],
  [184, "one hundred eighty-four", "ciento ochenta y cuatro"],
  [185, "one hundred eighty-five", "ciento ochenta y cinco"],
  [186, "one hundred eighty-six", "ciento ochenta y seis"],
  [187, "one hundred eighty-seven", "ciento ochenta y siete"],
  [188, "one hundred eighty-eight", "ciento ochenta y ocho"],
  [189, "one hundred eighty-nine", "ciento ochenta y nueve"],
  [190, "one hundred ninety", "ciento noventa"],
  [191, "one hundred ninety-one", "ciento noventa y uno"],
  [192, "one hundred ninety-two", "ciento noventa y dos"],
  [193, "one hundred ninety-three", "ciento noventa y tres"],
  [194, "one hundred ninety-four", "ciento noventa y cuatro"],
  [195, "one hundred ninety-five", "ciento noventa y cinco"],
  [196, "one hundred ninety-six", "ciento noventa y seis"],
  [197, "one hundred ninety-seven", "ciento noventa y siete"],
  [198, "one hundred ninety-eight", "ciento noventa y ocho"],
  [199, "one hundred ninety-nine", "ciento noventa y nueve"],
  [200, "two hundred", "doscientos"],
  [201, "two hundred one", "doscientos uno"],
  [202, "two hundred two", "doscientos dos"],
  [203, "two hundred three", "doscientos tres"],
  [204, "two hundred four", "doscientos cuatro"],
  [205, "two hundred five", "doscientos cinco"],
  [206, "two hundred six", "doscientos seis"],
  [207, "two hundred seven", "doscientos siete"],
  [208, "two hundred eight", "doscientos ocho"],
  [209, "two hundred nine", "doscientos nueve"],
  [210, "two hundred ten", "doscientos diez"],
  [211, "two hundred eleven", "doscientos once"],
  [212, "two hundred twelve", "doscientos doce"],
  [213, "two hundred thirteen", "doscientos trece"],
  [214, "two hundred fourteen", "doscientos catorce"],
  [215, "two hundred fifteen", "doscientos quince"],
  [216, "two hundred sixteen", "doscientos dieciséis"],
  [217, "two hundred seventeen", "doscientos diecisiete"],
  [218, "two hundred eighteen", "doscientos dieciocho"],
  [219, "two hundred nineteen", "doscientos diecinueve"],
  [220, "two hundred twenty", "doscientos veinte"],
  [221, "two hundred twenty-one", "doscientos veintiuno"],
  [222, "two hundred twenty-two", "doscientos veintidós"],
  [223, "two hundred twenty-three", "doscientos veintitrés"],
  [224, "two hundred twenty-four", "doscientos veinticuatro"],
  [225, "two hundred twenty-five", "doscientos veinticinco"],
  [226, "two hundred twenty-six", "doscientos veintiséis"],
  [227, "two hundred twenty-seven", "doscientos veintisiete"],
  [228, "two hundred twenty-eight", "doscientos veintiocho"],
  [229, "two hundred twenty-nine", "doscientos veintinueve"],
  [230, "two hundred thirty", "doscientos treinta"],
  [231, "two hundred thirty-one", "doscientos treinta y uno"],
  [232, "two hundred thirty-two", "doscientos treinta y dos"],
  [233, "two hundred thirty-three", "doscientos treinta y tres"],
  [234, "two hundred thirty-four", "doscientos treinta y cuatro"],
  [235, "two hundred thirty-five", "doscientos treinta y cinco"],
  [236, "two hundred thirty-six", "doscientos treinta y seis"],
  [237, "two hundred thirty-seven", "doscientos treinta y siete"],
  [238, "two hundred thirty-eight", "doscientos treinta y ocho"],
  [239, "two hundred thirty-nine", "doscientos treinta y nueve"],
  [240, "two hundred forty", "doscientos cuarenta"],
  [241, "two hundred forty-one", "doscientos cuarenta y uno"],
  [242, "two hundred forty-two", "doscientos cuarenta y dos"],
  [243, "two hundred forty-three", "doscientos cuarenta y tres"],
  [244, "two hundred forty-four", "doscientos cuarenta y cuatro"],
  [245, "two hundred forty-five", "doscientos cuarenta y cinco"],
  [246, "two hundred forty-six", "doscientos cuarenta y seis"],
  [247, "two hundred forty-seven", "doscientos cuarenta y siete"],
  [248, "two hundred forty-eight", "doscientos cuarenta y ocho"],
  [249, "two hundred forty-nine", "doscientos cuarenta y nueve"],
  [250, "two hundred fifty", "doscientos cincuenta"],
  [251, "two hundred fifty-one", "doscientos cincuenta y uno"],
  [252, "two hundred fifty-two", "doscientos cincuenta y dos"],
  [253, "two hundred fifty-three", "doscientos cincuenta y tres"],
  [254, "two hundred fifty-four", "doscientos cincuenta y cuatro"],
  [255, "two hundred fifty-five", "doscientos cincuenta y cinco"],
  [256, "two hundred fifty-six", "doscientos cincuenta y seis"],
  [257, "two hundred fifty-seven", "doscientos cincuenta y siete"],
  [258, "two hundred fifty-eight", "doscientos cincuenta y ocho"],
  [259, "two hundred fifty-nine", "doscientos cincuenta y nueve"],
  [260, "two hundred sixty", "doscientos sesenta"],
  [261, "two hundred sixty-one", "doscientos sesenta y uno"],
  [262, "two hundred sixty-two", "doscientos sesenta y dos"],
  [263, "two hundred sixty-three", "doscientos sesenta y tres"],
  [264, "two hundred sixty-four", "doscientos sesenta y cuatro"],
  [265, "two hundred sixty-five", "doscientos sesenta y cinco"],
  [266, "two hundred sixty-six", "doscientos sesenta y seis"],
  [267, "two hundred sixty-seven", "doscientos sesenta y siete"],
  [268, "two hundred sixty-eight", "doscientos sesenta y ocho"],
  [269, "two hundred sixty-nine", "doscientos sesenta y nueve"],
  [270, "two hundred seventy", "doscientos setenta"],
  [271, "two hundred seventy-one", "doscientos setenta y uno"],
  [272, "two hundred seventy-two", "doscientos setenta y dos"],
  [273, "two hundred seventy-three", "doscientos setenta y tres"],
  [274, "two hundred seventy-four", "doscientos setenta y cuatro"],
  [275, "two hundred seventy-five", "doscientos setenta y cinco"],
  [276, "two hundred seventy-six", "doscientos setenta y seis"],
  [277, "two hundred seventy-seven", "doscientos setenta y siete"],
  [278, "two hundred seventy-eight", "doscientos setenta y ocho"],
  [279, "two hundred seventy-nine", "doscientos setenta y nueve"],
  [280, "two hundred eighty", "doscientos ochenta"],
  [281, "two hundred eighty-one", "doscientos ochenta y uno"],
  [282, "two hundred eighty-two", "doscientos ochenta y dos"],
  [283, "two hundred eighty-three", "doscientos ochenta y tres"],
  [284, "two hundred eighty-four", "doscientos ochenta y cuatro"],
  [285, "two hundred eighty-five", "doscientos ochenta y cinco"],
  [286, "two hundred eighty-six", "doscientos ochenta y seis"],
  [287, "two hundred eighty-seven", "doscientos ochenta y siete"],
  [288, "two hundred eighty-eight", "doscientos ochenta y ocho"],
  [289, "two hundred eighty-nine", "doscientos ochenta y nueve"],
  [290, "two hundred ninety", "doscientos noventa"],
  [291, "two hundred ninety-one", "doscientos noventa y uno"],
  [292, "two hundred ninety-two", "doscientos noventa y dos"],
  [293, "two hundred ninety-three", "doscientos noventa y tres"],
  [294, "two hundred ninety-four", "doscientos noventa y cuatro"],
  [295, "two hundred ninety-five", "doscientos noventa y cinco"],
  [296, "two hundred ninety-six", "doscientos noventa y seis"],
  [297, "two hundred ninety-seven", "doscientos noventa y siete"],
  [298, "two hundred ninety-eight", "doscientos noventa y ocho"],
  [299, "two hundred ninety-nine", "doscientos noventa y nueve"],
  [300, "three hundred", "trescientos"],
  [301, "three hundred one", "trescientos uno"],
  [302, "three hundred two", "trescientos dos"],
  [303, "three hundred three", "trescientos tres"],
  [304, "three hundred four", "trescientos cuatro"],
  [305, "three hundred five", "trescientos cinco"],
  [306, "three hundred six", "trescientos seis"],
  [307, "three hundred seven", "trescientos siete"],
  [308, "three hundred eight", "trescientos ocho"],
  [309, "three hundred nine", "trescientos nueve"],
  [310, "three hundred ten", "trescientos diez"],
  [311, "three hundred eleven", "trescientos once"],
  [312, "three hundred twelve", "trescientos doce"],
  [313, "three hundred thirteen", "trescientos trece"],
  [314, "three hundred fourteen", "trescientos catorce"],
  [315, "three hundred fifteen", "trescientos quince"],
  [316, "three hundred sixteen", "trescientos dieciséis"],
  [317, "three hundred seventeen", "trescientos diecisiete"],
  [318, "three hundred eighteen", "trescientos dieciocho"],
  [319, "three hundred nineteen", "trescientos diecinueve"],
  [320, "three hundred twenty", "trescientos veinte"],
  [321, "three hundred twenty-one", "trescientos veintiuno"],
  [322, "three hundred twenty-two", "trescientos veintidós"],
  [323, "three hundred twenty-three", "trescientos veintitrés"],
  [324, "three hundred twenty-four", "trescientos veinticuatro"],
  [325, "three hundred twenty-five", "trescientos veinticinco"],
  [326, "three hundred twenty-six", "trescientos veintiséis"],
  [327, "three hundred twenty-seven", "trescientos veintisiete"],
  [328, "three hundred twenty-eight", "trescientos veintiocho"],
  [329, "three hundred twenty-nine", "trescientos veintinueve"],
  [330, "three hundred thirty", "trescientos treinta"],
  [331, "three hundred thirty-one", "trescientos treinta y uno"],
  [332, "three hundred thirty-two", "trescientos treinta y dos"],
  [333, "three hundred thirty-three", "trescientos treinta y tres"],
  [334, "three hundred thirty-four", "trescientos treinta y cuatro"],
  [335, "three hundred thirty-five", "trescientos treinta y cinco"],
  [336, "three hundred thirty-six", "trescientos treinta y seis"],
  [337, "three hundred thirty-seven", "trescientos treinta y siete"],
  [338, "three hundred thirty-eight", "trescientos treinta y ocho"],
  [339, "three hundred thirty-nine", "trescientos treinta y nueve"],
  [340, "three hundred forty", "trescientos cuarenta"],
  [341, "three hundred forty-one", "trescientos cuarenta y uno"],
  [342, "three hundred forty-two", "trescientos cuarenta y dos"],
  [343, "three hundred forty-three", "trescientos cuarenta y tres"],
  [344, "three hundred forty-four", "trescientos cuarenta y cuatro"],
  [345, "three hundred forty-five", "trescientos cuarenta y cinco"],
  [346, "three hundred forty-six", "trescientos cuarenta y seis"],
  [347, "three hundred forty-seven", "trescientos cuarenta y siete"],
  [348, "three hundred forty-eight", "trescientos cuarenta y ocho"],
  [349, "three hundred forty-nine", "trescientos cuarenta y nueve"],
  [350, "three hundred fifty", "trescientos cincuenta"],
  [351, "three hundred fifty-one", "trescientos cincuenta y uno"],
  [352, "three hundred fifty-two", "trescientos cincuenta y dos"],
  [353, "three hundred fifty-three", "trescientos cincuenta y tres"],
  [354, "three hundred fifty-four", "trescientos cincuenta y cuatro"],
  [355, "three hundred fifty-five", "trescientos cincuenta y cinco"],
  [356, "three hundred fifty-six", "trescientos cincuenta y seis"],
  [357, "three hundred fifty-seven", "trescientos cincuenta y siete"],
  [358, "three hundred fifty-eight", "trescientos cincuenta y ocho"],
  [359, "three hundred fifty-nine", "trescientos cincuenta y nueve"],
  [360, "three hundred sixty", "trescientos sesenta"],
  [361, "three hundred sixty-one", "trescientos sesenta y uno"],
  [362, "three hundred sixty-two", "trescientos sesenta y dos"],
  [363, "three hundred sixty-three", "trescientos sesenta y tres"],
  [364, "three hundred sixty-four", "trescientos sesenta y cuatro"],
  [365, "three hundred sixty-five", "trescientos sesenta y cinco"],
  [366, "three hundred sixty-six", "trescientos sesenta y seis"],
  [367, "three hundred sixty-seven", "trescientos sesenta y siete"],
  [368, "three hundred sixty-eight", "trescientos sesenta y ocho"],
  [369, "three hundred sixty-nine", "trescientos sesenta y nueve"],
  [370, "three hundred seventy", "trescientos setenta"],
  [371, "three hundred seventy-one", "trescientos setenta y uno"],
  [372, "three hundred seventy-two", "trescientos setenta y dos"],
  [373, "three hundred seventy-three", "trescientos setenta y tres"],
  [374, "three hundred seventy-four", "trescientos setenta y cuatro"],
  [375, "three hundred seventy-five", "trescientos setenta y cinco"],
  [376, "three hundred seventy-six", "trescientos setenta y seis"],
  [377, "three hundred seventy-seven", "trescientos setenta y siete"],
  [378, "three hundred seventy-eight", "trescientos setenta y ocho"],
  [379, "three hundred seventy-nine", "trescientos setenta y nueve"],
  [380, "three hundred eighty", "trescientos ochenta"],
  [381, "three hundred eighty-one", "trescientos ochenta y uno"],
  [382, "three hundred eighty-two", "trescientos ochenta y dos"],
  [383, "three hundred eighty-three", "trescientos ochenta y tres"],
  [384, "three hundred eighty-four", "trescientos ochenta y cuatro"],
  [385, "three hundred eighty-five", "trescientos ochenta y cinco"],
  [386, "three hundred eighty-six", "trescientos ochenta y seis"],
  [387, "three hundred eighty-seven", "trescientos ochenta y siete"],
  [388, "three hundred eighty-eight", "trescientos ochenta y ocho"],
  [389, "three hundred eighty-nine", "trescientos ochenta y nueve"],
  [390, "three hundred ninety", "trescientos noventa"],
  [391, "three hundred ninety-one", "trescientos noventa y uno"],
  [392, "three hundred ninety-two", "trescientos noventa y dos"],
  [393, "three hundred ninety-three", "trescientos noventa y tres"],
  [394, "three hundred ninety-four", "trescientos noventa y cuatro"],
  [395, "three hundred ninety-five", "trescientos noventa y cinco"],
  [396, "three hundred ninety-six", "trescientos noventa y seis"],
  [397, "three hundred ninety-seven", "trescientos noventa y siete"],
  [398, "three hundred ninety-eight", "trescientos noventa y ocho"],
  [399, "three hundred ninety-nine", "trescientos noventa y nueve"],
  [400, "four hundred", "cuatrocientos"],
  [401, "four hundred one", "cuatrocientos uno"],
  [402, "four hundred two", "cuatrocientos dos"],
  [403, "four hundred three", "cuatrocientos tres"],
  [404, "four hundred four", "cuatrocientos cuatro"],
  [405, "four hundred five", "cuatrocientos cinco"],
  [406, "four hundred six", "cuatrocientos seis"],
  [407, "four hundred seven", "cuatrocientos siete"],
  [408, "four hundred eight", "cuatrocientos ocho"],
  [409, "four hundred nine", "cuatrocientos nueve"],
  [410, "four hundred ten", "cuatrocientos diez"],
  [411, "four hundred eleven", "cuatrocientos once"],
  [412, "four hundred twelve", "cuatrocientos doce"],
  [413, "four hundred thirteen", "cuatrocientos trece"],
  [414, "four hundred fourteen", "cuatrocientos catorce"],
  [415, "four hundred fifteen", "cuatrocientos quince"],
  [416, "four hundred sixteen", "cuatrocientos dieciséis"],
  [417, "four hundred seventeen", "cuatrocientos diecisiete"],
  [418, "four hundred eighteen", "cuatrocientos dieciocho"],
  [419, "four hundred nineteen", "cuatrocientos diecinueve"],
  [420, "four hundred twenty", "cuatrocientos veinte"],
  [421, "four hundred twenty-one", "cuatrocientos veintiuno"],
  [422, "four hundred twenty-two", "cuatrocientos veintidós"],
  [423, "four hundred twenty-three", "cuatrocientos veintitrés"],
  [424, "four hundred twenty-four", "cuatrocientos veinticuatro"],
  [425, "four hundred twenty-five", "cuatrocientos veinticinco"],
  [426, "four hundred twenty-six", "cuatrocientos veintiséis"],
  [427, "four hundred twenty-seven", "cuatrocientos veintisiete"],
  [428, "four hundred twenty-eight", "cuatrocientos veintiocho"],
  [429, "four hundred twenty-nine", "cuatrocientos veintinueve"],
  [430, "four hundred thirty", "cuatrocientos treinta"],
  [431, "four hundred thirty-one", "cuatrocientos treinta y uno"],
  [432, "four hundred thirty-two", "cuatrocientos treinta y dos"],
  [433, "four hundred thirty-three", "cuatrocientos treinta y tres"],
  [434, "four hundred thirty-four", "cuatrocientos treinta y cuatro"],
  [435, "four hundred thirty-five", "cuatrocientos treinta y cinco"],
  [436, "four hundred thirty-six", "cuatrocientos treinta y seis"],
  [437, "four hundred thirty-seven", "cuatrocientos treinta y siete"],
  [438, "four hundred thirty-eight", "cuatrocientos treinta y ocho"],
  [439, "four hundred thirty-nine", "cuatrocientos treinta y nueve"],
  [440, "four hundred forty", "cuatrocientos cuarenta"],
  [441, "four hundred forty-one", "cuatrocientos cuarenta y uno"],
  [442, "four hundred forty-two", "cuatrocientos cuarenta y dos"],
  [443, "four hundred forty-three", "cuatrocientos cuarenta y tres"],
  [444, "four hundred forty-four", "cuatrocientos cuarenta y cuatro"],
  [445, "four hundred forty-five", "cuatrocientos cuarenta y cinco"],
  [446, "four hundred forty-six", "cuatrocientos cuarenta y seis"],
  [447, "four hundred forty-seven", "cuatrocientos cuarenta y siete"],
  [448, "four hundred forty-eight", "cuatrocientos cuarenta y ocho"],
  [449, "four hundred forty-nine", "cuatrocientos cuarenta y nueve"],
  [450, "four hundred fifty", "cuatrocientos cincuenta"],
  [451, "four hundred fifty-one", "cuatrocientos cincuenta y uno"],
  [452, "four hundred fifty-two", "cuatrocientos cincuenta y dos"],
  [453, "four hundred fifty-three", "cuatrocientos cincuenta y tres"],
  [454, "four hundred fifty-four", "cuatrocientos cincuenta y cuatro"],
  [455, "four hundred fifty-five", "cuatrocientos cincuenta y cinco"],
  [456, "four hundred fifty-six", "cuatrocientos cincuenta y seis"],
  [457, "four hundred fifty-seven", "cuatrocientos cincuenta y siete"],
  [458, "four hundred fifty-eight", "cuatrocientos cincuenta y ocho"],
  [459, "four hundred fifty-nine", "cuatrocientos cincuenta y nueve"],
  [460, "four hundred sixty", "cuatrocientos sesenta"],
  [461, "four hundred sixty-one", "cuatrocientos sesenta y uno"],
  [462, "four hundred sixty-two", "cuatrocientos sesenta y dos"],
  [463, "four hundred sixty-three", "cuatrocientos sesenta y tres"],
  [464, "four hundred sixty-four", "cuatrocientos sesenta y cuatro"],
  [465, "four hundred sixty-five", "cuatrocientos sesenta y cinco"],
  [466, "four hundred sixty-six", "cuatrocientos sesenta y seis"],
  [467, "four hundred sixty-seven", "cuatrocientos sesenta y siete"],
  [468, "four hundred sixty-eight", "cuatrocientos sesenta y ocho"],
  [469, "four hundred sixty-nine", "cuatrocientos sesenta y nueve"],
  [470, "four hundred seventy", "cuatrocientos setenta"],
  [471, "four hundred seventy-one", "cuatrocientos setenta y uno"],
  [472, "four hundred seventy-two", "cuatrocientos setenta y dos"],
  [473, "four hundred seventy-three", "cuatrocientos setenta y tres"],
  [474, "four hundred seventy-four", "cuatrocientos setenta y cuatro"],
  [475, "four hundred seventy-five", "cuatrocientos setenta y cinco"],
  [476, "four hundred seventy-six", "cuatrocientos setenta y seis"],
  [477, "four hundred seventy-seven", "cuatrocientos setenta y siete"],
  [478, "four hundred seventy-eight", "cuatrocientos setenta y ocho"],
  [479, "four hundred seventy-nine", "cuatrocientos setenta y nueve"],
  [480, "four hundred eighty", "cuatrocientos ochenta"],
  [481, "four hundred eighty-one", "cuatrocientos ochenta y uno"],
  [482, "four hundred eighty-two", "cuatrocientos ochenta y dos"],
  [483, "four hundred eighty-three", "cuatrocientos ochenta y tres"],
  [484, "four hundred eighty-four", "cuatrocientos ochenta y cuatro"],
  [485, "four hundred eighty-five", "cuatrocientos ochenta y cinco"],
  [486, "four hundred eighty-six", "cuatrocientos ochenta y seis"],
  [487, "four hundred eighty-seven", "cuatrocientos ochenta y siete"],
  [488, "four hundred eighty-eight", "cuatrocientos ochenta y ocho"],
  [489, "four hundred eighty-nine", "cuatrocientos ochenta y nueve"],
  [490, "four hundred ninety", "cuatrocientos noventa"],
  [491, "four hundred ninety-one", "cuatrocientos noventa y uno"],
  [492, "four hundred ninety-two", "cuatrocientos noventa y dos"],
  [493, "four hundred ninety-three", "cuatrocientos noventa y tres"],
  [494, "four hundred ninety-four", "cuatrocientos noventa y cuatro"],
  [495, "four hundred ninety-five", "cuatrocientos noventa y cinco"],
  [496, "four hundred ninety-six", "cuatrocientos noventa y seis"],
  [497, "four hundred ninety-seven", "cuatrocientos noventa y siete"],
  [498, "four hundred ninety-eight", "cuatrocientos noventa y ocho"],
  [499, "four hundred ninety-nine", "cuatrocientos noventa y nueve"],
  [500, "five hundred", "quinientos"],
  [501, "five hundred one", "quinientos uno"],
  [502, "five hundred two", "quinientos dos"],
  [503, "five hundred three", "quinientos tres"],
  [504, "five hundred four", "quinientos cuatro"],
  [505, "five hundred five", "quinientos cinco"],
  [506, "five hundred six", "quinientos seis"],
  [507, "five hundred seven", "quinientos siete"],
  [508, "five hundred eight", "quinientos ocho"],
  [509, "five hundred nine", "quinientos nueve"],
  [510, "five hundred ten", "quinientos diez"],
  [511, "five hundred eleven", "quinientos once"],
  [512, "five hundred twelve", "quinientos doce"],
  [513, "five hundred thirteen", "quinientos trece"],
  [514, "five hundred fourteen", "quinientos catorce"],
  [515, "five hundred fifteen", "quinientos quince"],
  [516, "five hundred sixteen", "quinientos dieciséis"],
  [517, "five hundred seventeen", "quinientos diecisiete"],
  [518, "five hundred eighteen", "quinientos dieciocho"],
  [519, "five hundred nineteen", "quinientos diecinueve"],
  [520, "five hundred twenty", "quinientos veinte"],
  [521, "five hundred twenty-one", "quinientos veintiuno"],
  [522, "five hundred twenty-two", "quinientos veintidós"],
  [523, "five hundred twenty-three", "quinientos veintitrés"],
  [524, "five hundred twenty-four", "quinientos veinticuatro"],
  [525, "five hundred twenty-five", "quinientos veinticinco"],
  [526, "five hundred twenty-six", "quinientos veintiséis"],
  [527, "five hundred twenty-seven", "quinientos veintisiete"],
  [528, "five hundred twenty-eight", "quinientos veintiocho"],
  [529, "five hundred twenty-nine", "quinientos veintinueve"],
  [530, "five hundred thirty", "quinientos treinta"],
  [531, "five hundred thirty-one", "quinientos treinta y uno"],
  [532, "five hundred thirty-two", "quinientos treinta y dos"],
  [533, "five hundred thirty-three", "quinientos treinta y tres"],
  [534, "five hundred thirty-four", "quinientos treinta y cuatro"],
  [535, "five hundred thirty-five", "quinientos treinta y cinco"],
  [536, "five hundred thirty-six", "quinientos treinta y seis"],
  [537, "five hundred thirty-seven", "quinientos treinta y siete"],
  [538, "five hundred thirty-eight", "quinientos treinta y ocho"],
  [539, "five hundred thirty-nine", "quinientos treinta y nueve"],
  [540, "five hundred forty", "quinientos cuarenta"],
  [541, "five hundred forty-one", "quinientos cuarenta y uno"],
  [542, "five hundred forty-two", "quinientos cuarenta y dos"],
  [543, "five hundred forty-three", "quinientos cuarenta y tres"],
  [544, "five hundred forty-four", "quinientos cuarenta y cuatro"],
  [545, "five hundred forty-five", "quinientos cuarenta y cinco"],
  [546, "five hundred forty-six", "quinientos cuarenta y seis"],
  [547, "five hundred forty-seven", "quinientos cuarenta y siete"],
  [548, "five hundred forty-eight", "quinientos cuarenta y ocho"],
  [549, "five hundred forty-nine", "quinientos cuarenta y nueve"],
  [550, "five hundred fifty", "quinientos cincuenta"],
  [551, "five hundred fifty-one", "quinientos cincuenta y uno"],
  [552, "five hundred fifty-two", "quinientos cincuenta y dos"],
  [553, "five hundred fifty-three", "quinientos cincuenta y tres"],
  [554, "five hundred fifty-four", "quinientos cincuenta y cuatro"],
  [555, "five hundred fifty-five", "quinientos cincuenta y cinco"],
  [556, "five hundred fifty-six", "quinientos cincuenta y seis"],
  [557, "five hundred fifty-seven", "quinientos cincuenta y siete"],
  [558, "five hundred fifty-eight", "quinientos cincuenta y ocho"],
  [559, "five hundred fifty-nine", "quinientos cincuenta y nueve"],
  [560, "five hundred sixty", "quinientos sesenta"],
  [561, "five hundred sixty-one", "quinientos sesenta y uno"],
  [562, "five hundred sixty-two", "quinientos sesenta y dos"],
  [563, "five hundred sixty-three", "quinientos sesenta y tres"],
  [564, "five hundred sixty-four", "quinientos sesenta y cuatro"],
  [565, "five hundred sixty-five", "quinientos sesenta y cinco"],
  [566, "five hundred sixty-six", "quinientos sesenta y seis"],
  [567, "five hundred sixty-seven", "quinientos sesenta y siete"],
  [568, "five hundred sixty-eight", "quinientos sesenta y ocho"],
  [569, "five hundred sixty-nine", "quinientos sesenta y nueve"],
  [570, "five hundred seventy", "quinientos setenta"],
  [571, "five hundred seventy-one", "quinientos setenta y uno"],
  [572, "five hundred seventy-two", "quinientos setenta y dos"],
  [573, "five hundred seventy-three", "quinientos setenta y tres"],
  [574, "five hundred seventy-four", "quinientos setenta y cuatro"],
  [575, "five hundred seventy-five", "quinientos setenta y cinco"],
  [576, "five hundred seventy-six", "quinientos setenta y seis"],
  [577, "five hundred seventy-seven", "quinientos setenta y siete"],
  [578, "five hundred seventy-eight", "quinientos setenta y ocho"],
  [579, "five hundred seventy-nine", "quinientos setenta y nueve"],
  [580, "five hundred eighty", "quinientos ochenta"],
  [581, "five hundred eighty-one", "quinientos ochenta y uno"],
  [582, "five hundred eighty-two", "quinientos ochenta y dos"],
  [583, "five hundred eighty-three", "quinientos ochenta y tres"],
  [584, "five hundred eighty-four", "quinientos ochenta y cuatro"],
  [585, "five hundred eighty-five", "quinientos ochenta y cinco"],
  [586, "five hundred eighty-six", "quinientos ochenta y seis"],
  [587, "five hundred eighty-seven", "quinientos ochenta y siete"],
  [588, "five hundred eighty-eight", "quinientos ochenta y ocho"],
  [589, "five hundred eighty-nine", "quinientos ochenta y nueve"],
  [590, "five hundred ninety", "quinientos noventa"],
  [591, "five hundred ninety-one", "quinientos noventa y uno"],
  [592, "five hundred ninety-two", "quinientos noventa y dos"],
  [593, "five hundred ninety-three", "quinientos noventa y tres"],
  [594, "five hundred ninety-four", "quinientos noventa y cuatro"],
  [595, "five hundred ninety-five", "quinientos noventa y cinco"],
  [596, "five hundred ninety-six", "quinientos noventa y seis"],
  [597, "five hundred ninety-seven", "quinientos noventa y siete"],
  [598, "five hundred ninety-eight", "quinientos noventa y ocho"],
  [599, "five hundred ninety-nine", "quinientos noventa y nueve"],
  [600, "six hundred", "seiscientos"],
  [601, "six hundred one", "seiscientos uno"],
  [602, "six hundred two", "seiscientos dos"],
  [603, "six hundred three", "seiscientos tres"],
  [604, "six hundred four", "seiscientos cuatro"],
  [605, "six hundred five", "seiscientos cinco"],
  [606, "six hundred six", "seiscientos seis"],
  [607, "six hundred seven", "seiscientos siete"],
  [608, "six hundred eight", "seiscientos ocho"],
  [609, "six hundred nine", "seiscientos nueve"],
  [610, "six hundred ten", "seiscientos diez"],
  [611, "six hundred eleven", "seiscientos once"],
  [612, "six hundred twelve", "seiscientos doce"],
  [613, "six hundred thirteen", "seiscientos trece"],
  [614, "six hundred fourteen", "seiscientos catorce"],
  [615, "six hundred fifteen", "seiscientos quince"],
  [616, "six hundred sixteen", "seiscientos dieciséis"],
  [617, "six hundred seventeen", "seiscientos diecisiete"],
  [618, "six hundred eighteen", "seiscientos dieciocho"],
  [619, "six hundred nineteen", "seiscientos diecinueve"],
  [620, "six hundred twenty", "seiscientos veinte"],
  [621, "six hundred twenty-one", "seiscientos veintiuno"],
  [622, "six hundred twenty-two", "seiscientos veintidós"],
  [623, "six hundred twenty-three", "seiscientos veintitrés"],
  [624, "six hundred twenty-four", "seiscientos veinticuatro"],
  [625, "six hundred twenty-five", "seiscientos veinticinco"],
  [626, "six hundred twenty-six", "seiscientos veintiséis"],
  [627, "six hundred twenty-seven", "seiscientos veintisiete"],
  [628, "six hundred twenty-eight", "seiscientos veintiocho"],
  [629, "six hundred twenty-nine", "seiscientos veintinueve"],
  [630, "six hundred thirty", "seiscientos treinta"],
  [631, "six hundred thirty-one", "seiscientos treinta y uno"],
  [632, "six hundred thirty-two", "seiscientos treinta y dos"],
  [633, "six hundred thirty-three", "seiscientos treinta y tres"],
  [634, "six hundred thirty-four", "seiscientos treinta y cuatro"],
  [635, "six hundred thirty-five", "seiscientos treinta y cinco"],
  [636, "six hundred thirty-six", "seiscientos treinta y seis"],
  [637, "six hundred thirty-seven", "seiscientos treinta y siete"],
  [638, "six hundred thirty-eight", "seiscientos treinta y ocho"],
  [639, "six hundred thirty-nine", "seiscientos treinta y nueve"],
  [640, "six hundred forty", "seiscientos cuarenta"],
  [641, "six hundred forty-one", "seiscientos cuarenta y uno"],
  [642, "six hundred forty-two", "seiscientos cuarenta y dos"],
  [643, "six hundred forty-three", "seiscientos cuarenta y tres"],
  [644, "six hundred forty-four", "seiscientos cuarenta y cuatro"],
  [645, "six hundred forty-five", "seiscientos cuarenta y cinco"],
  [646, "six hundred forty-six", "seiscientos cuarenta y seis"],
  [647, "six hundred forty-seven", "seiscientos cuarenta y siete"],
  [648, "six hundred forty-eight", "seiscientos cuarenta y ocho"],
  [649, "six hundred forty-nine", "seiscientos cuarenta y nueve"],
  [650, "six hundred fifty", "seiscientos cincuenta"],
  [651, "six hundred fifty-one", "seiscientos cincuenta y uno"],
  [652, "six hundred fifty-two", "seiscientos cincuenta y dos"],
  [653, "six hundred fifty-three", "seiscientos cincuenta y tres"],
  [654, "six hundred fifty-four", "seiscientos cincuenta y cuatro"],
  [655, "six hundred fifty-five", "seiscientos cincuenta y cinco"],
  [656, "six hundred fifty-six", "seiscientos cincuenta y seis"],
  [657, "six hundred fifty-seven", "seiscientos cincuenta y siete"],
  [658, "six hundred fifty-eight", "seiscientos cincuenta y ocho"],
  [659, "six hundred fifty-nine", "seiscientos cincuenta y nueve"],
  [660, "six hundred sixty", "seiscientos sesenta"],
  [661, "six hundred sixty-one", "seiscientos sesenta y uno"],
  [662, "six hundred sixty-two", "seiscientos sesenta y dos"],
  [663, "six hundred sixty-three", "seiscientos sesenta y tres"],
  [664, "six hundred sixty-four", "seiscientos sesenta y cuatro"],
  [665, "six hundred sixty-five", "seiscientos sesenta y cinco"],
  [666, "six hundred sixty-six", "seiscientos sesenta y seis"],
  [667, "six hundred sixty-seven", "seiscientos sesenta y siete"],
  [668, "six hundred sixty-eight", "seiscientos sesenta y ocho"],
  [669, "six hundred sixty-nine", "seiscientos sesenta y nueve"],
  [670, "six hundred seventy", "seiscientos setenta"],
  [671, "six hundred seventy-one", "seiscientos setenta y uno"],
  [672, "six hundred seventy-two", "seiscientos setenta y dos"],
  [673, "six hundred seventy-three", "seiscientos setenta y tres"],
  [674, "six hundred seventy-four", "seiscientos setenta y cuatro"],
  [675, "six hundred seventy-five", "seiscientos setenta y cinco"],
  [676, "six hundred seventy-six", "seiscientos setenta y seis"],
  [677, "six hundred seventy-seven", "seiscientos setenta y siete"],
  [678, "six hundred seventy-eight", "seiscientos setenta y ocho"],
  [679, "six hundred seventy-nine", "seiscientos setenta y nueve"],
  [680, "six hundred eighty", "seiscientos ochenta"],
  [681, "six hundred eighty-one", "seiscientos ochenta y uno"],
  [682, "six hundred eighty-two", "seiscientos ochenta y dos"],
  [683, "six hundred eighty-three", "seiscientos ochenta y tres"],
  [684, "six hundred eighty-four", "seiscientos ochenta y cuatro"],
  [685, "six hundred eighty-five", "seiscientos ochenta y cinco"],
  [686, "six hundred eighty-six", "seiscientos ochenta y seis"],
  [687, "six hundred eighty-seven", "seiscientos ochenta y siete"],
  [688, "six hundred eighty-eight", "seiscientos ochenta y ocho"],
  [689, "six hundred eighty-nine", "seiscientos ochenta y nueve"],
  [690, "six hundred ninety", "seiscientos noventa"],
  [691, "six hundred ninety-one", "seiscientos noventa y uno"],
  [692, "six hundred ninety-two", "seiscientos noventa y dos"],
  [693, "six hundred ninety-three", "seiscientos noventa y tres"],
  [694, "six hundred ninety-four", "seiscientos noventa y cuatro"],
  [695, "six hundred ninety-five", "seiscientos noventa y cinco"],
  [696, "six hundred ninety-six", "seiscientos noventa y seis"],
  [697, "six hundred ninety-seven", "seiscientos noventa y siete"],
  [698, "six hundred ninety-eight", "seiscientos noventa y ocho"],
  [699, "six hundred ninety-nine", "seiscientos noventa y nueve"],
  [700, "seven hundred", "setecientos"],
  [701, "seven hundred one", "setecientos uno"],
  [702, "seven hundred two", "setecientos dos"],
  [703, "seven hundred three", "setecientos tres"],
  [704, "seven hundred four", "setecientos cuatro"],
  [705, "seven hundred five", "setecientos cinco"],
  [706, "seven hundred six", "setecientos seis"],
  [707, "seven hundred seven", "setecientos siete"],
  [708, "seven hundred eight", "setecientos ocho"],
  [709, "seven hundred nine", "setecientos nueve"],
  [710, "seven hundred ten", "setecientos diez"],
  [711, "seven hundred eleven", "setecientos once"],
  [712, "seven hundred twelve", "setecientos doce"],
  [713, "seven hundred thirteen", "setecientos trece"],
  [714, "seven hundred fourteen", "setecientos catorce"],
  [715, "seven hundred fifteen", "setecientos quince"],
  [716, "seven hundred sixteen", "setecientos dieciséis"],
  [717, "seven hundred seventeen", "setecientos diecisiete"],
  [718, "seven hundred eighteen", "setecientos dieciocho"],
  [719, "seven hundred nineteen", "setecientos diecinueve"],
  [720, "seven hundred twenty", "setecientos veinte"],
  [721, "seven hundred twenty-one", "setecientos veintiuno"],
  [722, "seven hundred twenty-two", "setecientos veintidós"],
  [723, "seven hundred twenty-three", "setecientos veintitrés"],
  [724, "seven hundred twenty-four", "setecientos veinticuatro"],
  [725, "seven hundred twenty-five", "setecientos veinticinco"],
  [726, "seven hundred twenty-six", "setecientos veintiséis"],
  [727, "seven hundred twenty-seven", "setecientos veintisiete"],
  [728, "seven hundred twenty-eight", "setecientos veintiocho"],
  [729, "seven hundred twenty-nine", "setecientos veintinueve"],
  [730, "seven hundred thirty", "setecientos treinta"],
  [731, "seven hundred thirty-one", "setecientos treinta y uno"],
  [732, "seven hundred thirty-two", "setecientos treinta y dos"],
  [733, "seven hundred thirty-three", "setecientos treinta y tres"],
  [734, "seven hundred thirty-four", "setecientos treinta y cuatro"],
  [735, "seven hundred thirty-five", "setecientos treinta y cinco"],
  [736, "seven hundred thirty-six", "setecientos treinta y seis"],
  [737, "seven hundred thirty-seven", "setecientos treinta y siete"],
  [738, "seven hundred thirty-eight", "setecientos treinta y ocho"],
  [739, "seven hundred thirty-nine", "setecientos treinta y nueve"],
  [740, "seven hundred forty", "setecientos cuarenta"],
  [741, "seven hundred forty-one", "setecientos cuarenta y uno"],
  [742, "seven hundred forty-two", "setecientos cuarenta y dos"],
  [743, "seven hundred forty-three", "setecientos cuarenta y tres"],
  [744, "seven hundred forty-four", "setecientos cuarenta y cuatro"],
  [745, "seven hundred forty-five", "setecientos cuarenta y cinco"],
  [746, "seven hundred forty-six", "setecientos cuarenta y seis"],
  [747, "seven hundred forty-seven", "setecientos cuarenta y siete"],
  [748, "seven hundred forty-eight", "setecientos cuarenta y ocho"],
  [749, "seven hundred forty-nine", "setecientos cuarenta y nueve"],
  [750, "seven hundred fifty", "setecientos cincuenta"],
  [751, "seven hundred fifty-one", "setecientos cincuenta y uno"],
  [752, "seven hundred fifty-two", "setecientos cincuenta y dos"],
  [753, "seven hundred fifty-three", "setecientos cincuenta y tres"],
  [754, "seven hundred fifty-four", "setecientos cincuenta y cuatro"],
  [755, "seven hundred fifty-five", "setecientos cincuenta y cinco"],
  [756, "seven hundred fifty-six", "setecientos cincuenta y seis"],
  [757, "seven hundred fifty-seven", "setecientos cincuenta y siete"],
  [758, "seven hundred fifty-eight", "setecientos cincuenta y ocho"],
  [759, "seven hundred fifty-nine", "setecientos cincuenta y nueve"],
  [760, "seven hundred sixty", "setecientos sesenta"],
  [761, "seven hundred sixty-one", "setecientos sesenta y uno"],
  [762, "seven hundred sixty-two", "setecientos sesenta y dos"],
  [763, "seven hundred sixty-three", "setecientos sesenta y tres"],
  [764, "seven hundred sixty-four", "setecientos sesenta y cuatro"],
  [765, "seven hundred sixty-five", "setecientos sesenta y cinco"],
  [766, "seven hundred sixty-six", "setecientos sesenta y seis"],
  [767, "seven hundred sixty-seven", "setecientos sesenta y siete"],
  [768, "seven hundred sixty-eight", "setecientos sesenta y ocho"],
  [769, "seven hundred sixty-nine", "setecientos sesenta y nueve"],
  [770, "seven hundred seventy", "setecientos setenta"],
  [771, "seven hundred seventy-one", "setecientos setenta y uno"],
  [772, "seven hundred seventy-two", "setecientos setenta y dos"],
  [773, "seven hundred seventy-three", "setecientos setenta y tres"],
  [774, "seven hundred seventy-four", "setecientos setenta y cuatro"],
  [775, "seven hundred seventy-five", "setecientos setenta y cinco"],
  [776, "seven hundred seventy-six", "setecientos setenta y seis"],
  [777, "seven hundred seventy-seven", "setecientos setenta y siete"],
  [778, "seven hundred seventy-eight", "setecientos setenta y ocho"],
  [779, "seven hundred seventy-nine", "setecientos setenta y nueve"],
  [780, "seven hundred eighty", "setecientos ochenta"],
  [781, "seven hundred eighty-one", "setecientos ochenta y uno"],
  [782, "seven hundred eighty-two", "setecientos ochenta y dos"],
  [783, "seven hundred eighty-three", "setecientos ochenta y tres"],
  [784, "seven hundred eighty-four", "setecientos ochenta y cuatro"],
  [785, "seven hundred eighty-five", "setecientos ochenta y cinco"],
  [786, "seven hundred eighty-six", "setecientos ochenta y seis"],
  [787, "seven hundred eighty-seven", "setecientos ochenta y siete"],
  [788, "seven hundred eighty-eight", "setecientos ochenta y ocho"],
  [789, "seven hundred eighty-nine", "setecientos ochenta y nueve"],
  [790, "seven hundred ninety", "setecientos noventa"],
  [791, "seven hundred ninety-one", "setecientos noventa y uno"],
  [792, "seven hundred ninety-two", "setecientos noventa y dos"],
  [793, "seven hundred ninety-three", "setecientos noventa y tres"],
  [794, "seven hundred ninety-four", "setecientos noventa y cuatro"],
  [795, "seven hundred ninety-five", "setecientos noventa y cinco"],
  [796, "seven hundred ninety-six", "setecientos noventa y seis"],
  [797, "seven hundred ninety-seven", "setecientos noventa y siete"],
  [798, "seven hundred ninety-eight", "setecientos noventa y ocho"],
  [799, "seven hundred ninety-nine", "setecientos noventa y nueve"],
  [800, "eight hundred", "ochocientos"],
  [801, "eight hundred one", "ochocientos uno"],
  [802, "eight hundred two", "ochocientos dos"],
  [803, "eight hundred three", "ochocientos tres"],
  [804, "eight hundred four", "ochocientos cuatro"],
  [805, "eight hundred five", "ochocientos cinco"],
  [806, "eight hundred six", "ochocientos seis"],
  [807, "eight hundred seven", "ochocientos siete"],
  [808, "eight hundred eight", "ochocientos ocho"],
  [809, "eight hundred nine", "ochocientos nueve"],
  [810, "eight hundred ten", "ochocientos diez"],
  [811, "eight hundred eleven", "ochocientos once"],
  [812, "eight hundred twelve", "ochocientos doce"],
  [813, "eight hundred thirteen", "ochocientos trece"],
  [814, "eight hundred fourteen", "ochocientos catorce"],
  [815, "eight hundred fifteen", "ochocientos quince"],
  [816, "eight hundred sixteen", "ochocientos dieciséis"],
  [817, "eight hundred seventeen", "ochocientos diecisiete"],
  [818, "eight hundred eighteen", "ochocientos dieciocho"],
  [819, "eight hundred nineteen", "ochocientos diecinueve"],
  [820, "eight hundred twenty", "ochocientos veinte"],
  [821, "eight hundred twenty-one", "ochocientos veintiuno"],
  [822, "eight hundred twenty-two", "ochocientos veintidós"],
  [823, "eight hundred twenty-three", "ochocientos veintitrés"],
  [824, "eight hundred twenty-four", "ochocientos veinticuatro"],
  [825, "eight hundred twenty-five", "ochocientos veinticinco"],
  [826, "eight hundred twenty-six", "ochocientos veintiséis"],
  [827, "eight hundred twenty-seven", "ochocientos veintisiete"],
  [828, "eight hundred twenty-eight", "ochocientos veintiocho"],
  [829, "eight hundred twenty-nine", "ochocientos veintinueve"],
  [830, "eight hundred thirty", "ochocientos treinta"],
  [831, "eight hundred thirty-one", "ochocientos treinta y uno"],
  [832, "eight hundred thirty-two", "ochocientos treinta y dos"],
  [833, "eight hundred thirty-three", "ochocientos treinta y tres"],
  [834, "eight hundred thirty-four", "ochocientos treinta y cuatro"],
  [835, "eight hundred thirty-five", "ochocientos treinta y cinco"],
  [836, "eight hundred thirty-six", "ochocientos treinta y seis"],
  [837, "eight hundred thirty-seven", "ochocientos treinta y siete"],
  [838, "eight hundred thirty-eight", "ochocientos treinta y ocho"],
  [839, "eight hundred thirty-nine", "ochocientos treinta y nueve"],
  [840, "eight hundred forty", "ochocientos cuarenta"],
  [841, "eight hundred forty-one", "ochocientos cuarenta y uno"],
  [842, "eight hundred forty-two", "ochocientos cuarenta y dos"],
  [843, "eight hundred forty-three", "ochocientos cuarenta y tres"],
  [844, "eight hundred forty-four", "ochocientos cuarenta y cuatro"],
  [845, "eight hundred forty-five", "ochocientos cuarenta y cinco"],
  [846, "eight hundred forty-six", "ochocientos cuarenta y seis"],
  [847, "eight hundred forty-seven", "ochocientos cuarenta y siete"],
  [848, "eight hundred forty-eight", "ochocientos cuarenta y ocho"],
  [849, "eight hundred forty-nine", "ochocientos cuarenta y nueve"],
  [850, "eight hundred fifty", "ochocientos cincuenta"],
  [851, "eight hundred fifty-one", "ochocientos cincuenta y uno"],
  [852, "eight hundred fifty-two", "ochocientos cincuenta y dos"],
  [853, "eight hundred fifty-three", "ochocientos cincuenta y tres"],
  [854, "eight hundred fifty-four", "ochocientos cincuenta y cuatro"],
  [855, "eight hundred fifty-five", "ochocientos cincuenta y cinco"],
  [856, "eight hundred fifty-six", "ochocientos cincuenta y seis"],
  [857, "eight hundred fifty-seven", "ochocientos cincuenta y siete"],
  [858, "eight hundred fifty-eight", "ochocientos cincuenta y ocho"],
  [859, "eight hundred fifty-nine", "ochocientos cincuenta y nueve"],
  [860, "eight hundred sixty", "ochocientos sesenta"],
  [861, "eight hundred sixty-one", "ochocientos sesenta y uno"],
  [862, "eight hundred sixty-two", "ochocientos sesenta y dos"],
  [863, "eight hundred sixty-three", "ochocientos sesenta y tres"],
  [864, "eight hundred sixty-four", "ochocientos sesenta y cuatro"],
  [865, "eight hundred sixty-five", "ochocientos sesenta y cinco"],
  [866, "eight hundred sixty-six", "ochocientos sesenta y seis"],
  [867, "eight hundred sixty-seven", "ochocientos sesenta y siete"],
  [868, "eight hundred sixty-eight", "ochocientos sesenta y ocho"],
  [869, "eight hundred sixty-nine", "ochocientos sesenta y nueve"],
  [870, "eight hundred seventy", "ochocientos setenta"],
  [871, "eight hundred seventy-one", "ochocientos setenta y uno"],
  [872, "eight hundred seventy-two", "ochocientos setenta y dos"],
  [873, "eight hundred seventy-three", "ochocientos setenta y tres"],
  [874, "eight hundred seventy-four", "ochocientos setenta y cuatro"],
  [875, "eight hundred seventy-five", "ochocientos setenta y cinco"],
  [876, "eight hundred seventy-six", "ochocientos setenta y seis"],
  [877, "eight hundred seventy-seven", "ochocientos setenta y siete"],
  [878, "eight hundred seventy-eight", "ochocientos setenta y ocho"],
  [879, "eight hundred seventy-nine", "ochocientos setenta y nueve"],
  [880, "eight hundred eighty", "ochocientos ochenta"],
  [881, "eight hundred eighty-one", "ochocientos ochenta y uno"],
  [882, "eight hundred eighty-two", "ochocientos ochenta y dos"],
  [883, "eight hundred eighty-three", "ochocientos ochenta y tres"],
  [884, "eight hundred eighty-four", "ochocientos ochenta y cuatro"],
  [885, "eight hundred eighty-five", "ochocientos ochenta y cinco"],
  [886, "eight hundred eighty-six", "ochocientos ochenta y seis"],
  [887, "eight hundred eighty-seven", "ochocientos ochenta y siete"],
  [888, "eight hundred eighty-eight", "ochocientos ochenta y ocho"],
  [889, "eight hundred eighty-nine", "ochocientos ochenta y nueve"],
  [890, "eight hundred ninety", "ochocientos noventa"],
  [891, "eight hundred ninety-one", "ochocientos noventa y uno"],
  [892, "eight hundred ninety-two", "ochocientos noventa y dos"],
  [893, "eight hundred ninety-three", "ochocientos noventa y tres"],
  [894, "eight hundred ninety-four", "ochocientos noventa y cuatro"],
  [895, "eight hundred ninety-five", "ochocientos noventa y cinco"],
  [896, "eight hundred ninety-six", "ochocientos noventa y seis"],
  [897, "eight hundred ninety-seven", "ochocientos noventa y siete"],
  [898, "eight hundred ninety-eight", "ochocientos noventa y ocho"],
  [899, "eight hundred ninety-nine", "ochocientos noventa y nueve"],
  [900, "nine hundred", "novecientos"],
  [901, "nine hundred one", "novecientos uno"],
  [902, "nine hundred two", "novecientos dos"],
  [903, "nine hundred three", "novecientos tres"],
  [904, "nine hundred four", "novecientos cuatro"],
  [905, "nine hundred five", "novecientos cinco"],
  [906, "nine hundred six", "novecientos seis"],
  [907, "nine hundred seven", "novecientos siete"],
  [908, "nine hundred eight", "novecientos ocho"],
  [909, "nine hundred nine", "novecientos nueve"],
  [910, "nine hundred ten", "novecientos diez"],
  [911, "nine hundred eleven", "novecientos once"],
  [912, "nine hundred twelve", "novecientos doce"],
  [913, "nine hundred thirteen", "novecientos trece"],
  [914, "nine hundred fourteen", "novecientos catorce"],
  [915, "nine hundred fifteen", "novecientos quince"],
  [916, "nine hundred sixteen", "novecientos dieciséis"],
  [917, "nine hundred seventeen", "novecientos diecisiete"],
  [918, "nine hundred eighteen", "novecientos dieciocho"],
  [919, "nine hundred nineteen", "novecientos diecinueve"],
  [920, "nine hundred twenty", "novecientos veinte"],
  [921, "nine hundred twenty-one", "novecientos veintiuno"],
  [922, "nine hundred twenty-two", "novecientos veintidós"],
  [923, "nine hundred twenty-three", "novecientos veintitrés"],
  [924, "nine hundred twenty-four", "novecientos veinticuatro"],
  [925, "nine hundred twenty-five", "novecientos veinticinco"],
  [926, "nine hundred twenty-six", "novecientos veintiséis"],
  [927, "nine hundred twenty-seven", "novecientos veintisiete"],
  [928, "nine hundred twenty-eight", "novecientos veintiocho"],
  [929, "nine hundred twenty-nine", "novecientos veintinueve"],
  [930, "nine hundred thirty", "novecientos treinta"],
  [931, "nine hundred thirty-one", "novecientos treinta y uno"],
  [932, "nine hundred thirty-two", "novecientos treinta y dos"],
  [933, "nine hundred thirty-three", "novecientos treinta y tres"],
  [934, "nine hundred thirty-four", "novecientos treinta y cuatro"],
  [935, "nine hundred thirty-five", "novecientos treinta y cinco"],
  [936, "nine hundred thirty-six", "novecientos treinta y seis"],
  [937, "nine hundred thirty-seven", "novecientos treinta y siete"],
  [938, "nine hundred thirty-eight", "novecientos treinta y ocho"],
  [939, "nine hundred thirty-nine", "novecientos treinta y nueve"],
  [940, "nine hundred forty", "novecientos cuarenta"],
  [941, "nine hundred forty-one", "novecientos cuarenta y uno"],
  [942, "nine hundred forty-two", "novecientos cuarenta y dos"],
  [943, "nine hundred forty-three", "novecientos cuarenta y tres"],
  [944, "nine hundred forty-four", "novecientos cuarenta y cuatro"],
  [945, "nine hundred forty-five", "novecientos cuarenta y cinco"],
  [946, "nine hundred forty-six", "novecientos cuarenta y seis"],
  [947, "nine hundred forty-seven", "novecientos cuarenta y siete"],
  [948, "nine hundred forty-eight", "novecientos cuarenta y ocho"],
  [949, "nine hundred forty-nine", "novecientos cuarenta y nueve"],
  [950, "nine hundred fifty", "novecientos cincuenta"],
  [951, "nine hundred fifty-one", "novecientos cincuenta y uno"],
  [952, "nine hundred fifty-two", "novecientos cincuenta y dos"],
  [953, "nine hundred fifty-three", "novecientos cincuenta y tres"],
  [954, "nine hundred fifty-four", "novecientos cincuenta y cuatro"],
  [955, "nine hundred fifty-five", "novecientos cincuenta y cinco"],
  [956, "nine hundred fifty-six", "novecientos cincuenta y seis"],
  [957, "nine hundred fifty-seven", "novecientos cincuenta y siete"],
  [958, "nine hundred fifty-eight", "novecientos cincuenta y ocho"],
  [959, "nine hundred fifty-nine", "novecientos cincuenta y nueve"],
  [960, "nine hundred sixty", "novecientos sesenta"],
  [961, "nine hundred sixty-one", "novecientos sesenta y uno"],
  [962, "nine hundred sixty-two", "novecientos sesenta y dos"],
  [963, "nine hundred sixty-three", "novecientos sesenta y tres"],
  [964, "nine hundred sixty-four", "novecientos sesenta y cuatro"],
  [965, "nine hundred sixty-five", "novecientos sesenta y cinco"],
  [966, "nine hundred sixty-six", "novecientos sesenta y seis"],
  [967, "nine hundred sixty-seven", "novecientos sesenta y siete"],
  [968, "nine hundred sixty-eight", "novecientos sesenta y ocho"],
  [969, "nine hundred sixty-nine", "novecientos sesenta y nueve"],
  [970, "nine hundred seventy", "novecientos setenta"],
  [971, "nine hundred seventy-one", "novecientos setenta y uno"],
  [972, "nine hundred seventy-two", "novecientos setenta y dos"],
  [973, "nine hundred seventy-three", "novecientos setenta y tres"],
  [974, "nine hundred seventy-four", "novecientos setenta y cuatro"],
  [975, "nine hundred seventy-five", "novecientos setenta y cinco"],
  [976, "nine hundred seventy-six", "novecientos setenta y seis"],
  [977, "nine hundred seventy-seven", "novecientos setenta y siete"],
  [978, "nine hundred seventy-eight", "novecientos setenta y ocho"],
  [979, "nine hundred seventy-nine", "novecientos setenta y nueve"],
  [980, "nine hundred eighty", "novecientos ochenta"],
  [981, "nine hundred eighty-one", "novecientos ochenta y uno"],
  [982, "nine hundred eighty-two", "novecientos ochenta y dos"],
  [983, "nine hundred eighty-three", "novecientos ochenta y tres"],
  [984, "nine hundred eighty-four", "novecientos ochenta y cuatro"],
  [985, "nine hundred eighty-five", "novecientos ochenta y cinco"],
  [986, "nine hundred eighty-six", "novecientos ochenta y seis"],
  [987, "nine hundred eighty-seven", "novecientos ochenta y siete"],
  [988, "nine hundred eighty-eight", "novecientos ochenta y ocho"],
  [989, "nine hundred eighty-nine", "novecientos ochenta y nueve"],
  [990, "nine hundred ninety", "novecientos noventa"],
  [991, "nine hundred ninety-one", "novecientos noventa y uno"],
  [992, "nine hundred ninety-two", "novecientos noventa y dos"],
  [993, "nine hundred ninety-three", "novecientos noventa y tres"],
  [994, "nine hundred ninety-four", "novecientos noventa y cuatro"],
  [995, "nine hundred ninety-five", "novecientos noventa y cinco"],
  [996, "nine hundred ninety-six", "novecientos noventa y seis"],
  [997, "nine hundred ninety-seven", "novecientos noventa y siete"],
  [998, "nine hundred ninety-eight", "novecientos noventa y ocho"],
  [999, "nine hundred ninety-nine", "novecientos noventa y nueve"],
  [1000, "one thousand", "mil"],
  [9999, "", "nueve mil novecientos noventa y nueve"],
  [10000, "ten thousand", "diez mil"],
  [12139, "", "doce mil ciento treinta y nueve"],
];

test.concurrent.each(cases)("%d %s = %s", (number, english, spanish) => {
  expect(toSentence(LANGUAGES.spanish, number)).toEqual(spanish);
});
